# E-Commerce Revenue & Customer Analytics

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(
    r"C:\Users\riyaw\OneDrive\Desktop\Ecommerce-Analytics-Project\Dataset\Superstore.csv",
    encoding='latin1'
)

Data Exploration

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9994, 21)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

Data Quality Checks

In [7]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
df.duplicated().sum()

0

Data Type Conversion

In [9]:
df["Order Date"] = pd.to_datetime(df['Order Date'])
df["Ship Date"] = pd.to_datetime(df['Ship Date'])

verification

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

Feature Engineering

In [11]:
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month_name()

In [12]:
df[['Order Date', 'Order Year', 'Order Month']].head()

  Order Date  Order Year Order Month
0 2016-11-08        2016    November
1 2016-11-08        2016    November
2 2016-06-12        2016        June
3 2015-10-11        2015     October
4 2015-10-11        2015     October

In [13]:
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days

In [14]:
df[['Order Date', 'Ship Date', 'Shipping Days']].head()

  Order Date  Ship Date  Shipping Days
0 2016-11-08 2016-11-11              3
1 2016-11-08 2016-11-11              3
2 2016-06-12 2016-06-16              4
3 2015-10-11 2015-10-18              7
4 2015-10-11 2015-10-18              7

In [15]:
df['Sales'].sum()

2297200.8603000003

KPI Analysis

In [16]:
round(df['Sales'].sum(), 2)

2297200.86

In [17]:
round(df['Profit'].sum(), 2)

286397.02

In [18]:
profit_margin = (df['Profit'].sum() / df['Sales'].sum()) * 100

round(profit_margin, 2)

12.47

In [19]:
df['Order ID'].nunique()

5009

In [20]:
df['Customer ID'].nunique()

793

Category Analysis

In [21]:
# CATEGORY SALES ANALYSIS


category_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

print("Category-wise Sales")
print(category_sales)

print("\n")



# REGION SALES ANALYSIS


region_sales = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

print("Region-wise Sales")
print(region_sales)

print("\n")



# CATEGORY PROFIT ANALYSIS


category_profit = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

print("Category-wise Profit")
print(category_profit)

print("\n")



# MONTHLY SALES TREND


monthly_sales = df.groupby('Order Month')['Sales'].sum()

print("Monthly Sales Trend")
print(monthly_sales)

print("\n")



# AVERAGE DISCOUNT


average_discount = df['Discount'].mean()

print("Average Discount Given:", round(average_discount, 2))

Category-wise Sales
Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64


Region-wise Sales
Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64


Category-wise Profit
Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64


Monthly Sales Trend
Order Month
April        137762.1286
August       159044.0630
December     325293.5035
February      59751.2514
January       94924.8356
July         147238.0970
June         152718.6793
March        205005.4888
May          155028.8117
November     352461.0710
October      200322.9847
September    307649.9457
Name: Sales, dtype: float64


Average Discount Given: 0.16

In [22]:
category_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
category_profit = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)

print("Category Sales:\n", category_sales)
print("\nCategory Profit:\n", category_profit)

Category Sales:
 Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

Category Profit:
 Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

Category Performance Insight

- Technology generates the highest sales and profit contribution.
- Furniture shows high sales but extremely low profit.
- Office Supplies remains stable in both sales and profit.

**Conclusion:** Furniture category has margin inefficiency despite strong revenue contribution. ##

In [23]:
subcat_profit = df.groupby('Sub-Category')[['Sales','Profit']].sum().sort_values('Profit')

print(subcat_profit)

                    Sales      Profit
Sub-Category
Tables        206965.5320 -17725.4811
Bookcases     114879.9963  -3472.5560
Supplies       46673.5380  -1189.0995
Fasteners       3024.2800    949.5182
Machines      189238.6310   3384.7569
Labels         12486.3120   5546.2540
Art            27118.7920   6527.7870
Envelopes      16476.4020   6964.1767
Furnishings    91705.1640  13059.1436
Appliances    107532.1610  18138.0054
Storage       223843.6080  21278.8264
Chairs        328449.1030  26590.1663
Binders       203412.7330  30221.7633
Paper          78479.2060  34053.5693
Accessories   167380.3180  41936.6357
Phones        330007.0540  44515.7306
Copiers       149528.0300  55617.8249

Sub-Category Profit Insight

- Copiers, Phones, and Accessories are top profit contributors.
- Tables and Bookcases are loss-making sub-categories.
- Some products generate sales but reduce overall profitability.

**Conclusion:** Certain sub-categories are major profit leak points and need pricing/discount correction.

In [24]:
discount_profit = df.groupby('Discount')[['Sales','Profit']].mean()
corr = df[['Discount','Profit','Sales']].corr()

print("Discount vs Profit:\n", discount_profit)
print("\nCorrelation:\n", corr)

Discount vs Profit:
                Sales      Profit
Discount
0.00      226.742074   66.900292
0.10      578.397351   96.055074
0.15      529.971567   27.288298
0.20      209.076940   24.702572
0.30      454.742974  -45.679636
0.32      536.794770  -88.560656
0.40      565.134874 -111.927429
0.45      498.634000 -226.646464
0.50      892.705152 -310.703456
0.60       48.150000  -43.077212
0.70       97.177708  -95.874060
0.80       56.545853 -101.796797

Correlation:
           Discount    Profit     Sales
Discount  1.000000 -0.219487 -0.028190
Profit   -0.219487  1.000000  0.479064
Sales    -0.028190  0.479064  1.000000

Discount Impact Insight

- Higher discount levels (30%+) lead to negative profit.
- Low discount orders generate healthy margins.
- Strong negative correlation between discount and profit.

**Conclusion:** Discount strategy is reducing profitability and needs stricter control.

In [25]:
top_customers = df.groupby('Customer ID')[['Sales','Profit']].sum().sort_values('Sales', ascending=False).head(10)

customer_share = df.groupby('Customer ID')['Sales'].sum()
top_share = customer_share.sort_values(ascending=False).head(10) / customer_share.sum()

print("Top Customers:\n", top_customers)
print("\nRevenue Share:\n", top_share)

Top Customers:
                  Sales     Profit
Customer ID
SM-20320     25043.050 -1980.7393
TC-20980     19052.218  8981.3239
RB-19360     15117.339  6976.0959
TA-21385     14595.620  4703.7883
AB-10105     14473.571  5444.8055
KL-16645     14175.229   806.8550
SC-20095     14142.334  5757.4119
HL-15040     12873.298  5622.4292
SE-20110     12209.438  2650.6769
CC-12370     12129.072  2177.0493

Revenue Share:
 Customer ID
SM-20320    0.010902
TC-20980    0.008294
RB-19360    0.006581
TA-21385    0.006354
AB-10105    0.006301
KL-16645    0.006171
SC-20095    0.006156
HL-15040    0.005604
SE-20110    0.005315
CC-12370    0.005280
Name: Sales, dtype: float64

Customer Insight

- A small group of customers contributes significant revenue.
- Top customers show high dependency in overall revenue structure.
- Revenue distribution is uneven across customer base.

**Conclusion:** Business is dependent on a small set of high-value customers (risk concentration).

In [26]:
region_sales = df.groupby('Region')[['Sales','Profit']].sum().sort_values('Profit')

state_loss = df.groupby('State')[['Sales','Profit']].sum().sort_values('Profit').head(10)

print("Region Sales & Profit:\n", region_sales)
print("\nTop Loss States:\n", state_loss)

Region Sales & Profit:
                Sales       Profit
Region
Central  501239.8908   39706.3625
South    391721.9050   46749.4303
East     678781.2400   91522.7800
West     725457.8245  108418.4489

Top Loss States:
                       Sales      Profit
State
Texas           170188.0458 -25729.3563
Ohio             78258.1360 -16971.3766
Pennsylvania    116511.9140 -15559.9603
Illinois         80166.1010 -12607.8870
North Carolina   55603.1640  -7490.9122
Colorado         32108.1180  -6527.8579
Tennessee        30661.8730  -5341.6936
Arizona          35282.0010  -3427.9246
Florida          89473.7080  -3399.3017
Oregon           17431.1500  -1190.4705

Region Performance Insight

- West and East regions are highly profitable.
- Central region underperforms in profitability.
- States like Texas and Ohio show consistent losses.

**Conclusion:** Geographic imbalance exists between revenue and profitability.

In [27]:
monthly_sales = df.groupby('Order Month')['Sales'].sum()
monthly_profit = df.groupby('Order Month')['Profit'].sum()
yearly = df.groupby('Order Year')[['Sales','Profit']].sum()

print("Monthly Sales:\n", monthly_sales)
print("\nMonthly Profit:\n", monthly_profit)
print("\nYearly Trend:\n", yearly)

Monthly Sales:
 Order Month
April        137762.1286
August       159044.0630
December     325293.5035
February      59751.2514
January       94924.8356
July         147238.0970
June         152718.6793
March        205005.4888
May          155028.8117
November     352461.0710
October      200322.9847
September    307649.9457
Name: Sales, dtype: float64

Monthly Profit:
 Order Month
April        11587.4363
August       21776.9384
December     43369.1919
February     10294.6107
January       9134.4461
July         13832.6648
June         21285.7954
March        28594.6872
May          22411.3078
November     35468.4265
October      31784.0413
September    36857.4753
Name: Profit, dtype: float64

Yearly Trend:
                   Sales      Profit
Order Year
2014        484247.4981  49543.9741
2015        470532.5090  61618.6037
2016        609205.5980  81795.1743
2017        733215.2552  93439.2696

Time Trend Insight

- Sales and profit peak during November and December.
- Early months show weaker performance.
- Overall business shows consistent year-on-year growth.

**Conclusion:** Strong seasonal pattern exists with peak dependency on year-end demand.

In [28]:
df.to_csv("superstore_cleaned.csv", index=False)

In [29]:
!pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\riyaw\appdata\roaming\python\python310\site-packages (1.2.0)

In [30]:
import sys
!{sys.executable} -m pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\riyaw\appdata\roaming\python\python310\site-packages (1.2.0)

In [31]:
import pymysql
print("pymysql installed successfully")

pymysql installed successfully

In [32]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:password@localhost/ecommerce_analytics")

In [33]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [34]:
df["Order Date"] = df["Order Date"].dt.strftime("%Y-%m-%d")
df["Ship Date"] = df["Ship Date"].dt.strftime("%Y-%m-%d")

In [35]:
df.to_csv("superstore_mysql.csv", index=False)

In [36]:
df.columns = [
    "Row_ID",
    "Order_ID",
    "Order_Date",
    "Ship_Date",
    "Ship_Mode",
    "Customer_ID",
    "Customer_Name",
    "Segment",
    "Country",
    "City",
    "State",
    "Postal_Code",
    "Region",
    "Product_ID",
    "Category",
    "Sub_Category",
    "Product_Name",
    "Sales",
    "Quantity",
    "Discount",
    "Profit",
    "Order_Year",
    "Order_Month",
    "Shipping_Days"
]

In [37]:
df.to_csv("superstore_mysql_final.csv", index=False)

In [38]:
df["Sales"] = df["Sales"].astype(float)
df["Profit"] = df["Profit"].astype(float)
df["Discount"] = df["Discount"].astype(float)
df["Quantity"] = df["Quantity"].astype(int)
df["Shipping_Days"] = df["Shipping_Days"].astype(int)
df["Order_Year"] = df["Order_Year"].astype(int)

In [39]:
df.to_csv("superstore_sql_ready.csv", index=False)

In [40]:
import pymysql
from sqlalchemy import create_engine

In [41]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Wasnik$654@localhost/ecommerce_analytics"
)

In [42]:
df.to_sql("sales_fact", con=engine, if_exists="replace", index=False)

9994